"""Run a design in Verilator on our stimulus: the fast event-free CPU reference.

Verilator compiles the RTL to a C++ class. A generated main loads the stimulus
into memory, then for every (test, cycle) row applies the inputs, settles the
logic, samples the outputs and makes the clock edge. It prints the seconds spent
in that loop alone. What the timing leaves out, and how the threads share the
tests, is in the README under "What each column includes".
"""

import subprocess
from pathlib import Path

import numpy as np

from bitlane.icarus import driven_inputs
from bitlane.netlist import Netlist

MAIN = """\
// Generated by bitlane: replays the stimulus through the Verilated model of {top}.
// Built with: {command}
#include <atomic>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <thread>
#include <vector>

#include "V{top}.h"
#include "verilated.h"

struct Model {{
    VerilatedContext context;
    V{top} dut{{&context}};
}};

// One worker: its own model, a run of whole tests, one row per (test, cycle).
static void simulate(V{top} &dut, const uint64_t *stim, uint64_t *out, size_t rows) {{
    for (size_t row = 0; row < rows; row++, stim += {n_in}, out += {n_out}) {{
        {apply}  // apply the inputs
        {settle}
        {sample}  // sample the outputs
        {edge}
    }}
}}

int main(int, char **argv) {{
    // usage: V{top} <stimulus> <outputs> <tests> <cycles> <threads>
    size_t tests = atoll(argv[3]), cycles = atoll(argv[4]), threads = atoll(argv[5]);
    size_t rows = tests * cycles;
    std::vector<uint64_t> stim(rows * {n_in}), out(rows * {n_out});
    FILE *file = fopen(argv[1], "rb");
    if (!file || fread(stim.data(), 8, stim.size(), file) != stim.size()) return 1;
    fclose(file);
    std::vector<Model> models(threads);  // built before the clock starts

    // With several threads the workers start before the clock as well and wait at a
    // gate until all of them are running, so creating threads is never timed. Nor is a
    // model's first eval, which initialises it and takes a lock the workers queue on.
    std::atomic<size_t> ready{{0}}, done{{0}};
    std::atomic<bool> go{{false}};
    std::vector<std::thread> workers;
    for (size_t k = 0; threads > 1 && k < threads; k++) {{
        size_t first = tests * k / threads, last = tests * (k + 1) / threads;
        workers.emplace_back([&, k, first, last] {{
            models[k].dut.eval();
            ready++;
            while (!go) std::this_thread::yield();
            simulate(models[k].dut, &stim[first * cycles * {n_in}],
                     &out[first * cycles * {n_out}], (last - first) * cycles);
            done++;
        }});
    }}
    while (ready < workers.size()) std::this_thread::yield();
    // New threads start on their parent's core. Give the scheduler a moment to spread
    // the waiting workers over the cores, where a long-lived thread pool would be.
    if (threads > 1) std::this_thread::sleep_for(std::chrono::milliseconds(100));
    if (threads == 1) models[0].dut.eval();  // the same untimed first eval

    auto start = std::chrono::steady_clock::now();  // timed: the simulation only
    if (threads == 1) {{
        simulate(models[0].dut, stim.data(), out.data(), rows);
    }} else {{
        go = true;
        while (done < threads) std::this_thread::yield();
    }}
    std::chrono::duration<double> seconds = std::chrono::steady_clock::now() - start;
    for (auto &worker : workers) worker.join();

    for (auto &model : models) model.dut.final();
    file = fopen(argv[2], "wb");
    fwrite(out.data(), 8, out.size(), file);
    fclose(file);
    printf("%.9f\\n", seconds.count());
    return 0;
}}
"""


def build(verilog: Path, top: str, netlist: Netlist, workdir: Path) -> Path:
    """Verilate and compile `top` with a generated main; returns the executable.

    Skipped when the executable is newer than the Verilog and the generated main. The
    main records the build command, so a change of flags rebuilds too.
    """
    main, executable = workdir / "main.cpp", workdir / "obj" / f"V{top}"
    command = ["verilator", "--cc", "--exe", "--build", "-j", "0", "--top-module", top]
    command += ["-Wno-fatal"]  # legal Verilog with a lint warning still simulates
    command += ["-O3", "--x-assign", "fast", "--x-initial", "fast", "--noassert"]
    command += ["-CFLAGS", "-O3 -march=native", "-LDFLAGS", "-pthread"]
    # The makefile compiles the generated main, timed loop included, with OPT_FAST (-Os)
    # after the -CFLAGS above, and the last -O wins.
    command += ["-MAKEFLAGS", "OPT_FAST=-O3"]
    command += ["--Mdir", workdir / "obj", verilog, main]

    inputs, outputs = driven_inputs(netlist), list(netlist.outputs)
    clock = netlist.clock
    source = MAIN.format(
        top=top,
        command=" ".join(map(str, command)),
        n_in=len(inputs),
        n_out=len(outputs),
        apply=" ".join(f"dut.{name} = stim[{i}];" for i, name in enumerate(inputs)),
        settle=f"dut.{clock} = 0; dut.eval();" if clock else "dut.eval();",
        sample=" ".join(f"out[{i}] = dut.{name};" for i, name in enumerate(outputs)),
        edge=f"dut.{clock} = 1; dut.eval();  // the clock edge" if clock else "",
    )
    if not main.exists() or main.read_text() != source:
        main.write_text(source)
    newest_input = max(main.stat().st_mtime, verilog.stat().st_mtime)
    if executable.exists() and executable.stat().st_mtime > newest_input:
        return executable
    subprocess.run(command, check=True, stdout=subprocess.DEVNULL)
    return executable


def run_verilator(
    verilog: Path,
    top: str,
    netlist: Netlist,
    inputs: dict,
    workdir: Path,
    threads: int = 1,
) -> tuple[dict, float]:
    """Verilator's outputs for `inputs` (each (n_cycles, n_tests)) in the same shape,
    and the seconds its simulation loop took."""
    workdir = workdir.resolve()  # Verilator's make runs in obj/: keep paths absolute
    workdir.mkdir(parents=True, exist_ok=True)
    executable = build(verilog, top, netlist, workdir)
    n_cycles, n_tests = next(iter(inputs.values())).shape
    stim, out = workdir / "stim.bin", workdir / "out.bin"
    # One row per (test, cycle).
    columns = [inputs[name].T.reshape(-1) for name in driven_inputs(netlist)]
    np.stack(columns, axis=1).astype(np.uint64).tofile(stim)

    command = [executable, stim, out, str(n_tests), str(n_cycles), str(threads)]
    result = subprocess.run(command, check=True, capture_output=True, text=True)

    rows = np.fromfile(out, dtype=np.uint64).reshape(n_tests, n_cycles, -1)
    outputs = {name: rows[:, :, i].T for i, name in enumerate(netlist.outputs)}
    return outputs, float(result.stdout)
